### ISSUE TITLE
Ark Server-tools not updating

### ISSUE THREAD

**Issue by ghost** [bigdaddymccarron/ark#1]
Ark Server-Tools is not updating to the latest and the current version you in the docker image file will not allow steam to publish game online. 

`root@Tower:/ark# arkmanager --version`
`Version: 1.6`
`Channel: master`
`Blob SHA: ed9c34dca7486cc64880bc7cc3eda13ac1da2139`
`root@Tower:/ark# arkmanager upgrade-tools`
`arkmanager v1.6: Checking for updates...`
`Channel '${BRANCH}' does not exist`

`Available channels:`
`api`
`master`

**Comment by bigdaddymccarron** [comment]
This has been fixed.
